### ISSUE TITLE
Maybe change Google Pod dependency?

### ISSUE THREAD

**Issue by marinehero** [tomvanlieshout/elpee#1]
Just downloaded to test and got:
Build input file cannot be found: '/Users/owner/Downloads/GoogleService-Info.plist'

which traces back to project.pbxproj:
		E28E698D23FC776B00D5CC2D /* GoogleService-Info.plist */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = text.plist.xml; name = "GoogleService-Info.plist"; path = "**../../../../Downloads/GoogleService-Info.plist**"; sourceTree = "<group>"; };

should one use "pod Google/SignIn" instead of "pod Google"?

**Comment by tomvanlieshout** [comment]
Hi James,

Thank you for your interest in elpee! The error *Build input file cannot be
found: '/Users/owner/Downloads/GoogleService-Info.plist' *is caused because
I included the file GoogleService-Info.plist in my .gitignore, as it
contains sensitive information.
I'm going to look for a way to include this file without exposing it.

Kind regards,

Tom van Lieshout

Op wo 11 mrt. 2020 om 20:33 schreef James Pereira <notifications@github.com
